feat(ci): update codecheck items

diff --git a/.github/workflows/code_check.yml b/.github/workflows/code_check.yml
--- a/.github/workflows/code_check.yml
+++ b/.github/workflows/code_check.yml
@@ -1,6 +1,7 @@
 name: Code check
 
 on:   
+  workflow_dispatch:
   push:
     branches: [ main ]
     paths-ignore:
@@ -20,7 +21,7 @@ on:
 
 jobs:
 
-  gofmt:
+  fmtvet:
     runs-on: ubuntu-latest
     steps:
     - name: Set up Go
@@ -31,10 +32,15 @@ jobs:
     - name: Check out source code
       uses: actions/checkout@v1
 
-    - name: Run go fmt
-      run: d="$(gofmt -d ../../)" && if [ -n "$d" ]; then echo "format error:" ; echo "$d"; exit 1; fi      
+    - name: Run go fmt/vet
+      run: |
+        make fmt
+        make vet
 
-  check-crd:
+    - name: Check
+      run: d="$(git status -s)" && if [ -n "$d" ]; then echo "check-crd error:" ; echo "$d"; exit 1; fi 
+
+  checkcrd:
     runs-on: ubuntu-latest
     steps:
     - name: Set up Go
@@ -46,10 +52,12 @@ jobs:
       uses: actions/checkout@v1
 
     - name: Recreate crd
-      run: make manifests
+      run: |
+        make manifests
+        make generate
 
     - name: Check crd
-      run: diff charts/mysql-operator/crds config/crd/bases
+      run: d="$(git status -s)" && if [ -n "$d" ]; then echo "check-crd error:" ; echo "$d"; exit 1; fi 
 
   staticcheck:
     runs-on: ubuntu-latest
@@ -67,3 +75,17 @@ jobs:
 
     - name: Run staticcheck
       run: staticcheck -f stylish ./... 
+
+  build:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Set up Go
+      uses: actions/setup-go@v2
+      with:
+        go-version: 1.16
+
+    - name: Check out source code
+      uses: actions/checkout@v1
+
+    - name: Make build
+      run: make build
